### ISSUE TITLE
After installing, `dokku` command hangs

### ISSUE THREAD

**Issue by parndt** [cedricziel/dokku-hostkeys-plugin#25] opened 2016-05-27 03:54 UTC
This is what happens, in screenshot form:

<img width="960" alt="screen shot 2016-05-27 at 15 53 42" src="https://cloud.githubusercontent.com/assets/10128/15597339/3802ef88-2423-11e6-8d31-0e7237d0e7c3.png">

There is no further output.  Removing this plugin resolves the issue.

**Comment by jaunkst** [comment] 2016-06-22 03:50
+1

**Comment by ajunge** [comment] 2016-10-27 21:52
The problem is with the new dokku 0.7.2

**Comment by ineffyble** [comment] 2016-11-18 06:45
Here's the debug code:

`+ for community_plugin_command in '$COMMUNITY_PLUGIN_COMMANDS'
+ /var/lib/dokku/plugins/enabled/hostkeys-plugin/commands help
+ APP=
+ SHARED_KEY_TO_ADD=
+ SHARED_KEY_TO_ADD_APP=
+ HOSTNAME_TO_ADD=
+ HOSTNAME_TO_ADD_APP=
+ HOSTNAME_TO_REMOVE=
+ HOSTNAME_TO_REMOVE_APP=
+ APP_SPECIFIC_HOSTKEYS_FOLDER=/home/dokku/.hostkeys//.ssh
+ APP_SPECIFIC_HOSTKEYS_FILE=/home/dokku/.hostkeys//.ssh/known_hosts
+ SHARED_HOSTKEYS_FOLDER=/home/dokku/.hostkeys/shared/.ssh
+ SHARED_HOSTKEYS_FILE=/home/dokku/.hostkeys/shared/.ssh/known_hosts
+ case "$1" in
+ cat`

**Comment by tonyivanz** [comment] 2016-12-12 12:40
Does anyone have a fix for this issue?

**Comment by michaelshobbs** [comment] 2016-12-12 16:02
These forks of [hostkeys](https://github.com/michaelshobbs/dokku-hostkeys-plugin) and [deployment-keys](https://github.com/michaelshobbs/dokku-deployment-keys) work with `0.7.x`. Note: I use them daily

**Closed** 2016-12-12 20:59 UTC
